// Qué se estudia en cada campus/sede (principales). Clave: nombre original en lmlist.js
module.exports={
"PUC – Casa Central":"Derecho, Medicina, Ciencias Biológicas y Comunicaciones (Periodismo); también rectoría y el Hospital Clínico.",
"PUC – Campus San Joaquín":"El campus más grande de la UC: Ingeniería, Ingeniería Comercial, College, Matemáticas, Física, Química, Agronomía, Psicología, Educación, Ciencias Sociales, Historia y Ciencia Política, Letras, Filosofía, Teología, Enfermería, Odontología y Construcción Civil.",
"PUC – Campus Lo Contador":"Arquitectura, Diseño y Estudios Urbanos.",
"PUC – Campus Oriente":"Artes: Arte, Música y Teatro (Actuación).",
"U. de Chile – Casa Central":"Rectoría y administración central (no se dictan carreras).",
"U. de Chile – Beauchef (FCFM)":"Ingeniería y Ciencias (Plan Común), Geología, Física, Astronomía.",
"U. de Chile – Juan Gómez Millas":"Ciencias (Biología, Química, Matemáticas), Filosofía y Humanidades, Ciencias Sociales (Psicología, Sociología, Antropología), Periodismo y Cine (ICEI), parte de Artes.",
"U. de Chile – Facultad de Derecho":"Derecho.",
"U. de Chile – Campus Norte (Medicina)":"Medicina, Enfermería, Kinesiología y demás carreras de la salud; al lado, Odontología y Química y Farmacia.",
"U. de Chile – Campus Andrés Bello (FEN)":"Ingeniería Comercial, Contador Auditor e Ingeniería en Información y Control de Gestión.",
"U. de Chile – Campus Sur (Agronomía)":"Agronomía, Medicina Veterinaria e Ingeniería Forestal (campus Antumapu).",
"U. de Chile – FAU (Arquitectura)":"Arquitectura, Diseño y Geografía.",
"USACH":"Campus único: fuerte en Ingeniería (heredera de la U. Técnica del Estado), además de Medicina, Química y Biología, Administración y Economía, Humanidades y Pedagogías.",
"Universidad del Desarrollo (UDD)":"Ingeniería Comercial, Derecho, Medicina y carreras de la salud, Ingeniería, Diseño, Arquitectura, Periodismo, Psicología.",
"Universidad de los Andes":"Medicina, Odontología y Enfermería, Derecho, Ingeniería Comercial, Ingeniería, Psicología, Educación, Comunicación.",
"Universidad Finis Terrae":"Derecho, Medicina y Odontología, Artes Visuales, Teatro, Arquitectura, Diseño, Ingeniería Comercial.",
"Universidad Adolfo Ibáñez – Peñalolén":"Pregrado de la UAI en Santiago: Ingeniería Comercial, Ingeniería Civil, Derecho, Psicología, Periodismo y Diseño.",
"UAI – sede Presidente Errázuriz":"Postgrados y educación ejecutiva (MBA, magísteres); el pregrado está en Peñalolén.",
"Universidad Gabriela Mistral":"Derecho, Ingeniería Comercial, Psicología y carreras de salud y educación.",
"Universidad San Sebastián – Bellavista":"Derecho, Ingeniería Comercial, Arquitectura, Psicología y Educación, entre otras.",
"Universidad San Sebastián – Los Leones":"Principalmente carreras de la salud: Medicina, Odontología, Enfermería, Kinesiología, Medicina Veterinaria.",
"Universidad Santo Tomás – Santiago":"Universidad, Instituto Profesional y CFT Santo Tomás: Derecho, Psicología, salud, Medicina Veterinaria y carreras técnicas.",
"INACAP Apoquindo":"Sede de INACAP (universidad, IP y CFT): gastronomía y hotelería, administración, informática, diseño.",
"INACAP Santiago Centro":"Sede de INACAP: administración y negocios, informática, salud, humanidades.",
"INACAP Maipú":"Sede de INACAP: mecánica y electromovilidad, electricidad, construcción, administración, informática.",
"INACAP Renca":"Sede de INACAP: fuerte en mecánica automotriz, maquinaria, minería, logística y procesos industriales.",
"INACAP Puente Alto":"Sede de INACAP: administración, informática, salud, electricidad y mecánica.",
"Duoc UC – Plaza Oeste":"Sede de Duoc UC: administración y negocios, informática, salud, turismo.",
"Duoc UC – sede San Joaquín":"Sede de Duoc UC: ingeniería (mecánica, electricidad, automatización), informática, construcción, salud y diseño.",
"Duoc UC – sede Alameda":"Sede de Duoc UC: construcción, informática y telecomunicaciones, administración.",
"Duoc UC – sede Padre Alonso de Ovalle":"Sede de Duoc UC: administración y negocios, turismo y hotelería, informática.",
"Duoc UC – sede Maipú":"Sede de Duoc UC: administración, informática, salud, construcción, ingeniería.",
"Duoc UC – sede Puente Alto":"Sede de Duoc UC: administración, informática, salud, mecánica y electricidad.",
"AIEP – sede Bellavista":"Instituto profesional AIEP: carreras técnicas y profesionales de salud, estética, gastronomía, diseño, negocios, sonido.",
"Universidad Diego Portales":"Derecho, Psicología, Periodismo, Arquitectura, Diseño, Ingeniería, Ingeniería Comercial y Medicina, repartidas en el barrio universitario (Ejército / Vergara / Manuel Rodríguez).",
"Universidad Alberto Hurtado":"Universidad jesuita: Derecho, Psicología, Educación, Ciencias Sociales, Filosofía, Economía y Negocios.",
"Universidad Andrés Bello – República":"El campus más grande de la UNAB: salud (Medicina, Odontología, Enfermería), Ingeniería, Ciencias, Educación, Psicología.",
"Universidad Andrés Bello – Casona de Las Condes":"Ingeniería Comercial, Derecho, Arquitectura, Diseño, Periodismo y parte de salud e ingeniería.",
"Universidad Mayor – Manuel Montt":"Ingeniería, Ingeniería Comercial, Derecho, Arquitectura, Diseño y Artes.",
"Universidad Mayor – Huechuraba":"Salud (Medicina, Odontología, Enfermería), Medicina Veterinaria, Agronomía, Psicología, Educación.",
"UTEM":"Universidad estatal: casa central (rectoría). Sus ingenierías, Diseño, Arquitectura y Administración se dictan sobre todo en el campus Macul (José Pedro Alessandri) y el campus Providencia.",
"UMCE (ex Pedagógico)":"Universidad estatal de educación: pedagogías en todas las áreas (el ex Pedagógico de la U. de Chile).",
"Universidad Central":"Derecho, Arquitectura, Ingeniería, Psicología, Educación, Economía y Administración, salud.",
"Universidad Autónoma":"Derecho, salud (Medicina, Odontología, Enfermería), Educación, Ingeniería, Administración.",
"UTFSM – Campus San Joaquín":"Ingenierías civiles (Industrial, Informática, Eléctrica, Mecánica, Química, Minas…) e Ingeniería Comercial; la casa central está en Valparaíso.",
"UTFSM – Campus Vitacura":"Ingeniería Comercial, Ingeniería Civil Industrial, Ingeniería en Aviación Comercial, Arquitectura y postgrados.",
"Universidad Bernardo O'Higgins":"Derecho, salud (Enfermería, Kinesiología, Obstetricia), Educación, Ingeniería, Psicología.",
"Universidad Católica Silva Henríquez":"Pedagogías, Trabajo Social, Psicología, Derecho, salud.",
"Universidad de las Américas (campus Providencia)":"Derecho, Ingeniería y Negocios, salud, Educación, Arquitectura y Diseño, Psicología, Medicina Veterinaria.",
"Universidad Academia de Humanismo Cristiano":"Ciencias sociales (Sociología, Antropología, Trabajo Social), Derecho, Psicología, Pedagogías, Danza y Teatro."
};
