// [name, category, nominatim query, expected comuna, short description]
module.exports=[
// --- Centro y gobierno
["Palacio de La Moneda","Gobierno y justicia","Palacio de La Moneda","Santiago","Sede de la Presidencia, entre la Plaza de la Constitución (norte) y la Plaza de la Ciudadanía (Alameda)."],
["Plaza de Armas","Centro histórico","Plaza de Armas, Santiago","Santiago","Kilómetro cero de la ciudad, con la Catedral Metropolitana."],
["Mercado Central","Centro histórico","Mercado Central de Santiago","Santiago","Mercado de pescados y mariscos junto al Mapocho."],
["La Vega Central","Centro histórico","La Vega Central","Recoleta","Mercado de frutas y verduras, al norte del Mapocho."],
["Estación Mapocho","Centro histórico","Centro Cultural Estación Mapocho","Santiago","Antigua estación de trenes, hoy centro cultural, junto al río."],
["Biblioteca Nacional","Centro histórico","Biblioteca Nacional de Chile","Santiago","En la Alameda, al pie del cerro Santa Lucía."],
["Teatro Municipal","Centro histórico","Teatro Municipal de Santiago","Santiago","Teatro de ópera y ballet en calle Agustinas."],
["Barrio Cívico / Paseo Bulnes","Gobierno y justicia","Paseo Bulnes","Santiago","Eje al sur de La Moneda, cruzando la Alameda."],
["Ex Congreso Nacional","Gobierno y justicia","Ex Congreso Nacional","Santiago","Antiguo Congreso, a una cuadra de la Plaza de Armas. Desde 1990 el Congreso (Cámara y Senado) sesiona en Valparaíso; aquí se hacen algunas sesiones y actividades del Senado en Santiago."],
["Palacio de Tribunales","Gobierno y justicia","Palacio de los Tribunales de Justicia","Santiago","Sede de la Corte Suprema y de la Corte de Apelaciones de Santiago, frente al ex Congreso."],
["Plaza Italia (Plaza Baquedano)","Centro histórico","Plaza Baquedano","Providencia","El punto donde se unen Alameda, Providencia y Vicuña Mackenna. Límite simbólico oriente/poniente."],
["Estación Central (ferrocarriles)","Transporte","Estación Central de Santiago","Estación Central","Terminal de trenes al sur (EFE), en la Alameda."],
["Paseo Ahumada","Centro histórico","Paseo Ahumada","Santiago","Calle peatonal principal del centro, de la Alameda a la Plaza de Armas."],
["Cementerio General","Centro histórico","Cementerio General de Santiago","Recoleta","El gran cementerio histórico, en Recoleta."],
// --- Cerros y parques
["Cerro San Cristóbal (cumbre, Virgen)","Cerros y parques","Santuario Inmaculada Concepción, Cerro San Cristóbal","Recoleta","El cerro del Parque Metropolitano, con la Virgen en la cumbre."],
["Zoológico Nacional","Cerros y parques","Zoológico Nacional de Chile","Recoleta","En la ladera del San Cristóbal, entrando por Pío Nono (Bellavista)."],
["Cerro Santa Lucía","Cerros y parques","Cerro Santa Lucía","Santiago","Cerro en pleno centro, en la Alameda."],
["Parque Forestal","Cerros y parques","Parque Forestal","Santiago","Parque lineal en la ribera sur del Mapocho, de Plaza Italia al Mercado Central."],
["Parque Bustamante","Cerros y parques","Parque Bustamante","Providencia","Parque lineal desde Plaza Italia hacia el sur."],
["Parque Bicentenario (Vitacura)","Cerros y parques","Parque Bicentenario, Vitacura","Vitacura","Parque con lagunas junto al Mapocho, frente a la Municipalidad de Vitacura."],
["Parque Araucano","Cerros y parques","Parque Araucano","Las Condes","Parque junto al Mall Parque Arauco, entre Kennedy y Riesco."],
["Parque O'Higgins","Cerros y parques","Parque O'Higgins","Santiago","Gran parque al sur del centro: Movistar Arena, Fantasilandia, fondas."],
["Parque Quinta Normal","Cerros y parques","Parque Quinta Normal","Quinta Normal","Parque con museos (Historia Natural), en Matucana."],
["Parque Balmaceda","Cerros y parques","Parque Balmaceda","Providencia","Parque lineal en la ribera sur del Mapocho, en Providencia."],
["Parque de las Esculturas","Cerros y parques","Parque de las Esculturas","Providencia","Junto al Mapocho, al frente de Pedro de Valdivia Norte."],
["Parque Inés de Suárez","Cerros y parques","Parque Inés de Suárez","Providencia","Parque en Antonio Varas con Pocuro/Bilbao."],
["Parque Juan Pablo II","Cerros y parques","Parque Juan Pablo II, Las Condes","Las Condes","Parque en Américo Vespucio con Kennedy/Apoquindo sur."],
["Parque Padre Hurtado","Cerros y parques","Parque Padre Hurtado, La Reina","La Reina","Gran parque al pie de los cerros, en Francisco Bilbao / Padre Hurtado (ex Parque Intercomunal)."],
["Parque Mahuida","Cerros y parques","Parque Mahuida","La Reina","Parque precordillerano al final de Av. Larraín."],
["Parque de los Reyes","Cerros y parques","Parque de los Reyes","Santiago","Parque junto al Mapocho, al poniente de la Estación Mapocho."],
["Cerro Manquehue","Cerros y parques","Cerro Manquehue","Vitacura","El cerro puntiagudo al norte de Vitacura/Lo Barnechea."],
["Cerro Calán (Observatorio)","Cerros y parques","Observatorio Cerro Calán","Las Condes","Cerro con el observatorio de la U. de Chile, en Las Condes."],
["Cerro Renca","Cerros y parques","Cerro Renca","Renca","Cerro grande al norponiente."],
["Cerro Blanco","Cerros y parques","Cerro Blanco, Recoleta","Recoleta","Cerro en Recoleta, junto a la estación Cerro Blanco (L2)."],
["Cerro Chena","Cerros y parques","Cerro Chena","San Bernardo","Cerro en San Bernardo, al sur."],
["Parque André Jarlán","Cerros y parques","Parque André Jarlán","Pedro Aguirre Cerda","Parque en PAC, al sur de la Av. Carlos Valdovinos."],
["Parque Bicentenario de Cerrillos","Cerros y parques","Parque Bicentenario de Cerrillos","Cerrillos","Parque en el ex aeródromo de Cerrillos."],
["Parque Intercomunal de La Reina","Cerros y parques","Parque Intercomunal de La Reina","La Reina","(fallback)"],
["Pueblito Los Dominicos","Cerros y parques","Pueblito Los Dominicos","Las Condes","Feria de artesanía al final de Apoquindo, junto a la Iglesia Los Dominicos."],
["Parque Metropolitano Sur (Cerro Chena?)","",null,null,null],
// --- Deporte
["Estadio Monumental (Colo-Colo)","Deporte","Estadio Monumental David Arellano","Macul","Estadio de Colo-Colo, en Av. Departamental con Marathon."],
["Estadio Nacional","Deporte","Estadio Nacional Julio Martínez Prádanos","Ñuñoa","El estadio nacional, en Av. Grecia con Pedro de Valdivia / Marathon."],
["Claro Arena (ex San Carlos de Apoquindo)","Deporte","Claro Arena","Las Condes","Estadio de la UC, en San Carlos de Apoquindo."],
["Estadio Santa Laura","Deporte","Estadio Santa Laura","Independencia","Estadio de Unión Española."],
["Estadio Bicentenario de La Florida","Deporte","Estadio Bicentenario Municipal de La Florida","La Florida","Estadio de Audax Italiano."],
["Estadio El Teniente? no","",null,null,null],
["Movistar Arena","Deporte","Movistar Arena","Santiago","Arena de conciertos dentro del Parque O'Higgins."],
["Club Hípico de Santiago","Deporte","Club Hípico de Santiago","Santiago","Hipódromo en Av. Blanco Encalada, al sur del centro."],
["Hipódromo Chile","Deporte","Hipódromo Chile","Independencia","Hipódromo en Independencia."],
["Estadio Español","Deporte","Estadio Español","Las Condes","Club deportivo en Av. Las Condes."],
["Prince of Wales Country Club","Deporte","Prince of Wales Country Club","La Reina","Club de golf en Av. Príncipe de Gales / Las Arañas."],
["Estadio Municipal de La Cisterna","Deporte","Estadio Municipal de La Cisterna","La Cisterna","Estadio de Palestino."],
// --- Comercio y edificios
["Costanera Center / Gran Torre Santiago","Malls y edificios","Costanera Center","Providencia","El edificio más alto de Sudamérica, junto a Tobalaba con Andrés Bello."],
["Torre Entel","Malls y edificios","Torre Entel","Santiago","Torre de telecomunicaciones junto a la Alameda."],
["Sanhattan (El Golf / Isidora Goyenechea)","Malls y edificios","Isidora Goyenechea, Las Condes","Las Condes","El distrito financiero: El Golf, Isidora Goyenechea, Titanium."],
["Parque Arauco","Malls y edificios","Mall Parque Arauco","Las Condes","Mall en Av. Kennedy con Américo Vespucio."],
["Alto Las Condes","Malls y edificios","Mall Alto Las Condes","Las Condes","Mall en Av. Kennedy con Padre Hurtado."],
["Mall Plaza Egaña","Malls y edificios","Mall Plaza Egaña","La Reina","Mall en Plaza Egaña (Ossa con Larraín)."],
["Mall Plaza Vespucio","Malls y edificios","Mall Plaza Vespucio","La Florida","Mall en Vicuña Mackenna con Américo Vespucio."],
["Mall Florida Center","Malls y edificios","Mall Florida Center","La Florida","Mall en Vicuña Mackenna, sur de Plaza Vespucio."],
["Mall Plaza Oeste","Malls y edificios","Mall Plaza Oeste","Cerrillos","Mall en Américo Vespucio con Autopista Central/ Lo Espejo."],
["Mall Plaza Norte","Malls y edificios","Mall Plaza Norte","Huechuraba","Mall en Américo Vespucio con Panamericana Norte."],
["Mall Arauco Maipú","Malls y edificios","Mall Arauco Maipú","Maipú","Mall en Américo Vespucio con Pajaritos."],
["Mall Plaza Tobalaba","Malls y edificios","Mall Plaza Tobalaba","Puente Alto","Mall en Camilo Henríquez, Puente Alto."],
["Mall Sport","Malls y edificios","Mall Sport","Las Condes","Mall deportivo en Av. Las Condes."],
["Portal La Dehesa","Malls y edificios","Portal La Dehesa","Lo Barnechea","Mall en Av. La Dehesa."],
["Apumanque","Malls y edificios","Mall Apumanque","Las Condes","Centro comercial en Apoquindo con Manquehue."],
["Mall Plaza Los Dominicos","Malls y edificios","Mall Plaza Los Dominicos","Las Condes","Mall en Padre Hurtado con Apoquindo."],
["Mall Costanera? dup","",null,null,null],
["Patronato","Barrios","Barrio Patronato","Recoleta","Barrio comercial de ropa, en Recoleta."],
["Persa Bío Bío","Barrios","Persa Bío Bío","Santiago","Mercado persa en el barrio Franklin."],
["Barrio Meiggs","Barrios","Barrio Meiggs","Estación Central","Comercio popular junto a la Estación Central."],
// --- Barrios
["Barrio Italia","Barrios","Barrio Italia, Providencia","Providencia","Tiendas de diseño y cafés en Av. Italia, entre Providencia y Ñuñoa."],
["Barrio Lastarria","Barrios","Barrio Lastarria","Santiago","Barrio bohemio al pie del cerro Santa Lucía."],
["Barrio Bellavista","Barrios","Barrio Bellavista","Providencia","Vida nocturna entre Pío Nono y el San Cristóbal (comparten Recoleta y Providencia)."],
["Barrio Yungay","Barrios","Barrio Yungay","Santiago","Barrio patrimonial al poniente del centro."],
["Barrio Brasil","Barrios","Plaza Brasil, Santiago","Santiago","Barrio universitario y bohemio en torno a Plaza Brasil."],
["Barrio República","Barrios","Avenida República, Santiago","Santiago","Barrio universitario (UNAB, UDP, U. Central, UCh FEN cerca) en la Av. República."],
["Barrio Franklin","Barrios","Barrio Franklin","Santiago","Mataderos y persas al sur del centro."],
["Plaza Ñuñoa","Barrios","Plaza Ñuñoa","Ñuñoa","Corazón de Ñuñoa, en Irarrázaval con Jorge Washington."],
["Plaza Egaña","Barrios","Plaza Egaña","Ñuñoa","Cruce de Irarrázaval, Ossa y Larraín (Ñuñoa/La Reina)."],
["Barrio El Golf","Barrios","El Golf, Las Condes","Las Condes","Barrio financiero y de embajadas en Las Condes."],
["Pedro de Valdivia Norte","Barrios","Pedro de Valdivia Norte","Providencia","Barrio residencial al norte del Mapocho, al pie del San Cristóbal."],
["Barrio Suecia","Barrios","Avenida Suecia, Providencia","Providencia","Antiguo barrio de bares en Suecia con Providencia."],
["Plaza Las Lilas","Barrios","Plaza Las Lilas","Providencia","Plaza en Eliodoro Yáñez, Providencia oriente."],
["Pueblo de Lo Barnechea","Barrios","Lo Barnechea pueblo","Lo Barnechea","El pueblo antiguo, hacia la cordillera."],
["Chicureo","Barrios","Chicureo","Colina","Sector residencial en Colina, al norte de Santiago."],
["Ciudad Empresarial","Barrios","Ciudad Empresarial, Huechuraba","Huechuraba","Parque de oficinas en Huechuraba."],
["Plaza de Maipú","Barrios","Plaza de Maipú","Maipú","Centro de Maipú, término de la L5."],
["Plaza de Puente Alto","Barrios","Plaza de Puente Alto","Puente Alto","Centro de Puente Alto, término de la L4."],
["Plaza de San Bernardo","Barrios","Plaza de Armas de San Bernardo","San Bernardo","Centro de San Bernardo."],
// --- Cultura
["Museo de Bellas Artes","Cultura","Museo Nacional de Bellas Artes","Santiago","En el Parque Forestal."],
["GAM","Cultura","Centro Cultural Gabriela Mistral","Santiago","Centro cultural en la Alameda, cerca de Plaza Italia."],
["Museo de la Memoria","Cultura","Museo de la Memoria y los Derechos Humanos","Santiago","En Matucana, frente al Parque Quinta Normal."],
["Museo Nacional de Historia Natural","Cultura","Museo Nacional de Historia Natural","Quinta Normal","Dentro del Parque Quinta Normal."],
["Museo Precolombino","Cultura","Museo Chileno de Arte Precolombino","Santiago","A una cuadra de la Plaza de Armas."],
["Museo Interactivo Mirador (MIM)","Cultura","Museo Interactivo Mirador","La Granja","Museo de ciencias para niños, en La Granja."],
["Fantasilandia","Cultura","Fantasilandia","Santiago","Parque de diversiones en el Parque O'Higgins."],
["Templo Votivo de Maipú","Religión","Templo Votivo de Maipú","Maipú","Gran santuario en Maipú, donde fue la batalla de Maipú."],
["Templo Bahá'í","Religión","Templo Bahá'í de Sudamérica","Peñalolén","Templo blanco en la precordillera de Peñalolén."],
["La Chascona (casa de Neruda)","Cultura","La Chascona","Providencia","Casa de Neruda en Bellavista."],
["Planetario USACH","Cultura","Planetario Universidad de Santiago","Estación Central","Junto a la USACH, en la Alameda."],
["Matucana 100","Cultura","Matucana 100","Estación Central","Centro cultural en Matucana."],
["Teatro Caupolicán","Cultura","Teatro Caupolicán","Santiago","Recinto de conciertos en San Diego."],
["Basílica de Lourdes","Religión","Gruta de Lourdes, Quinta Normal","Quinta Normal","Santuario en Quinta Normal (estación Gruta de Lourdes)."],
["Santuario Padre Hurtado","Religión","Santuario Padre Hurtado","Estación Central","Santuario en Estación Central."],
// --- Salud
["Clínica Las Condes","Salud","Clínica Las Condes","Las Condes","Clínica en el sector Estoril / Lo Fontecilla."],
["Clínica Alemana","Salud","Clínica Alemana Vitacura","Vitacura","Clínica en Av. Vitacura / Manquehue Norte."],
["Clínica Santa María","Salud","Clínica Santa María","Providencia","Clínica junto al Mapocho, en Bellavista/Santa María."],
["Hospital Clínico UC (Marcoleta)","Salud","Hospital Clínico UC Christus","Santiago","Hospital de la UC en Marcoleta, cerca de la Alameda."],
["Hospital Clínico U. de Chile (J.J. Aguirre)","Salud","Hospital Clínico Universidad de Chile","Independencia","En el sector de hospitales de Independencia."],
["Posta Central","Salud","Hospital de Urgencia Asistencia Pública","Santiago","Principal urgencia pública, en Portugal con la Alameda."],
["Hospital del Salvador","Salud","Hospital del Salvador","Providencia","Hospital en Av. Salvador, Providencia."],
["Hospital Militar","Salud","Hospital Militar de Santiago","La Reina","Hospital en La Reina."],
["Hospital Sótero del Río","Salud","Hospital Sótero del Río","Puente Alto","Gran hospital público en Puente Alto."],
["Clínica Dávila","Salud","Clínica Dávila","Recoleta","Clínica en Recoleta."],
// --- Transporte
["Aeropuerto Arturo Merino Benítez","Transporte","Aeropuerto Internacional Arturo Merino Benítez","Pudahuel","Aeropuerto internacional, en Pudahuel."],
["Terminal Sur / Alameda (buses)","Transporte","Terminal Alameda","Estación Central","Terminales de buses interurbanos junto a la estación Universidad de Santiago."],
["Terminal San Borja","Transporte","Terminal San Borja","Estación Central","Terminal de buses junto a la Estación Central."],
// --- Universidades
["PUC – Casa Central","Universidades","Casa Central Pontificia Universidad Católica","Santiago","Edificio histórico de la UC en la Alameda (estación Universidad Católica)."],
["PUC – Campus San Joaquín","Universidades","Campus San Joaquín Pontificia Universidad Católica","Macul","Campus principal de la UC, en Vicuña Mackenna (estación San Joaquín)."],
["PUC – Campus Lo Contador","Universidades","Campus Lo Contador","Providencia","Arquitectura y diseño UC, en El Comendador, Providencia."],
["PUC – Campus Oriente","Universidades","Campus Oriente Pontificia Universidad Católica","Providencia","Artes y teología UC, en Av. Jaime Guzmán (sector Diagonal Oriente)."],
["U. de Chile – Casa Central","Universidades","Casa Central Universidad de Chile","Santiago","Edificio histórico en la Alameda (estación U. de Chile)."],
["U. de Chile – Beauchef (FCFM)","Universidades","Facultad de Ciencias Físicas y Matemáticas Universidad de Chile","Santiago","Ingeniería U. de Chile, en Beauchef, junto al Parque O'Higgins."],
["U. de Chile – Juan Gómez Millas","Universidades","Campus Juan Gómez Millas","Ñuñoa","Campus en Av. Grecia / Ignacio Carrera Pinto, Ñuñoa."],
["U. de Chile – Facultad de Derecho","Universidades","Facultad de Derecho Universidad de Chile","Recoleta","En Pío Nono, junto al Mapocho."],
["U. de Chile – Campus Norte (Medicina)","Universidades","Facultad de Medicina Universidad de Chile","Independencia","Medicina U. de Chile, en Independencia."],
["U. de Chile – Campus Andrés Bello (FEN)","Universidades","Facultad de Economía y Negocios Universidad de Chile","Santiago","FEN, en Diagonal Paraguay, cerca de la Alameda."],
["U. de Chile – Campus Sur (Agronomía)","Universidades","Campus Sur Universidad de Chile","La Pintana","Agronomía y veterinaria, en La Pintana."],
["USACH","Universidades","Universidad de Santiago de Chile","Estación Central","Campus en la Alameda, Estación Central."],
["Universidad del Desarrollo (UDD)","Universidades","Universidad del Desarrollo, Las Condes","Las Condes","Campus en Av. Plaza, San Carlos de Apoquindo."],
["Universidad de los Andes","Universidades","Universidad de los Andes, Monseñor Álvaro del Portillo","Las Condes","Campus en San Carlos de Apoquindo."],
["Universidad Finis Terrae","Universidades","Universidad Finis Terrae","Providencia","Campus en Av. Pedro de Valdivia."],
["Universidad Adolfo Ibáñez – Peñalolén","Universidades","Universidad Adolfo Ibáñez Peñalolén","Peñalolén","Campus en Diagonal Las Torres, Peñalolén."],
["Universidad Gabriela Mistral","Universidades","Universidad Gabriela Mistral","Providencia","Campus en Av. Ricardo Lyon."],
["Universidad San Sebastián – Bellavista","Universidades","Universidad San Sebastián Bellavista","Recoleta","Campus Bellavista, junto al Mapocho."],
["Universidad San Sebastián – Los Leones","Universidades","Universidad San Sebastián Los Leones","Providencia","Campus en Lota / Los Leones."],
["Universidad Santo Tomás – Santiago","Universidades","Universidad Santo Tomás Santiago","Santiago","Sede en Av. Ejército, barrio República."],
["INACAP Apoquindo","Universidades","INACAP Apoquindo","Las Condes","Sede en Apoquindo, Las Condes."],
["INACAP Santiago Centro","Universidades","INACAP Santiago Centro","Santiago","Sede en el centro."],
["Duoc UC – San Carlos de Apoquindo","Universidades","Duoc UC San Carlos de Apoquindo","Las Condes","Sede en Camino El Alba."],
["Duoc UC – Antonio Varas","Universidades","Duoc UC Antonio Varas","Providencia","Sede en Antonio Varas."],
["Duoc UC – Plaza Oeste","Universidades","Duoc UC Plaza Oeste","Cerrillos","Sede junto al Mall Plaza Oeste."],
["Universidad Diego Portales","Universidades","Universidad Diego Portales","Santiago","Barrio universitario de Santiago (Ejército / Vergara)."],
["Universidad Alberto Hurtado","Universidades","Universidad Alberto Hurtado","Santiago","Barrio universitario (Almirante Barroso / Cienfuegos)."],
["Universidad Andrés Bello – República","Universidades","Universidad Andrés Bello República","Santiago","Sede en Av. República."],
["Universidad Andrés Bello – Casona de Las Condes","Universidades","Universidad Andrés Bello Casona de Las Condes","Las Condes","Campus en Fernández Concha, Las Condes."],
["Universidad Mayor – Manuel Montt","Universidades","Universidad Mayor Manuel Montt","Providencia","Campus en Av. Manuel Montt."],
["Universidad Mayor – Huechuraba","Universidades","Universidad Mayor Huechuraba","Huechuraba","Campus en Camino La Pirámide."],
["UTEM","Universidades","Universidad Tecnológica Metropolitana","Ñuñoa","Campus Macul en José Pedro Alessandri."],
["UMCE (ex Pedagógico)","Universidades","Universidad Metropolitana de Ciencias de la Educación","Ñuñoa","Ex Pedagógico, en José Pedro Alessandri."],
["Universidad Central","Universidades","Universidad Central de Chile","Santiago","Sede en Lord Cochrane / Toesca."],
["Universidad Autónoma","Universidades","Universidad Autónoma de Chile Santiago","Providencia","Sede en Pedro de Valdivia."],
["Universidad del Pacífico? no","",null,null,null],
// --- Colegios
["Instituto Nacional","Colegios","Instituto Nacional General José Miguel Carrera","Santiago","Liceo emblemático en la Alameda, junto a la U. de Chile."],
["Liceo 1 Javiera Carrera","Colegios","Liceo 1 Javiera Carrera","Santiago","Liceo emblemático de niñas, centro."],
["Liceo Carmela Carvajal","Colegios","Liceo Carmela Carvajal de Prat","Providencia","Liceo emblemático de Providencia."],
["Liceo Lastarria","Colegios","Liceo José Victorino Lastarria","Providencia","Liceo de Providencia."],
["INBA","Colegios","Internado Nacional Barros Arana","Santiago","Internado emblemático en Quinta Normal / Santiago poniente."],
["Liceo Manuel de Salas","Colegios","Liceo Experimental Manuel de Salas","Ñuñoa","En Brown Norte, Ñuñoa."],
["Colegio Verbo Divino","Colegios","Colegio del Verbo Divino","Las Condes","En Av. Presidente Errázuriz, Las Condes."],
["Villa María Academy","Colegios","Villa María Academy","Las Condes","En Av. Presidente Errázuriz, Las Condes."],
["Colegio San Ignacio El Bosque","Colegios","Colegio San Ignacio El Bosque","Providencia","En Av. Pocuro, Providencia."],
["Colegio San Ignacio Alonso Ovalle","Colegios","Colegio San Ignacio Alonso Ovalle","Santiago","En el centro, calle Alonso Ovalle."],
["Saint George's College","Colegios","Saint George's College","Vitacura","En Av. Santa Teresa de Los Andes, Vitacura (sector Lo Curro)."],
["Colegio SEK","Colegios","International School SEK Chile","Peñalolén","SEK Chile."],
["The Grange School","Colegios","The Grange School","La Reina","En Av. Príncipe de Gales, La Reina."],
["Nido de Águilas","Colegios","Nido de Águilas","Lo Barnechea","Colegio internacional en Lo Barnechea."],
["Santiago College","Colegios","Santiago College","Lo Barnechea","En Camino Los Trapenses, Lo Barnechea."],
["Colegio Alemán (Vitacura)","Colegios","Deutsche Schule Santiago","Las Condes","Colegio Alemán de Santiago."],
["Lycée Antoine de Saint-Exupéry","Colegios","Lycée Antoine de Saint-Exupéry","Vitacura","Colegio francés en Vitacura."],
["Colegio Manquehue","Colegios","Colegio Manquehue","Vitacura","Colegio benedictino en Vitacura (Santa María de Manquehue)."],
["Colegio Craighouse","Colegios","Craighouse School","Lo Barnechea","Colegio en Lo Barnechea."],
["Colegio Apoquindo? skip","",null,null,null],
// --- Restaurantes y bares
["Fuente Alemana","Restaurantes y bares","Fuente Alemana","Santiago","Lomitos icónicos, frente a Plaza Italia (Alameda)."],
["Bar Liguria (Providencia)","Restaurantes y bares","Liguria Manuel Montt","Providencia","Bar-restaurante clásico en Providencia."],
["La Piojera","Restaurantes y bares","La Piojera","Santiago","Bar del terremoto, al lado del Mercado Central."],
["Confitería Torres","Restaurantes y bares","Confitería Torres","Santiago","Restaurante histórico en la Alameda."],
["Bar Nacional","Restaurantes y bares","Bar Nacional, Huérfanos","Santiago","Fuente de soda tradicional del centro."],
["Boragó","Restaurantes y bares","Boragó","Vitacura","Restaurante de alta cocina en Vitacura."],
["Castillo Forestal","Restaurantes y bares","Castillo Forestal","Santiago","Restaurante en un castillo, en el Parque Forestal."],
["Mercado Tirso de Molina","Restaurantes y bares","Mercado Tirso de Molina","Recoleta","Cocinerías y frutas junto a La Vega."],
// --- Gobierno y justicia (agregados)
["Centro de Justicia de Santiago","Gobierno y justicia","Centro de Justicia de Santiago","Santiago","Juzgados de garantía y tribunales orales en lo penal, en Av. Pedro Montt (al sur del Parque O'Higgins). Aquí se ven las causas penales de Santiago."],
["Tribunal Constitucional","Gobierno y justicia","Tribunal Constitucional de Chile","Santiago","Revisa que las leyes respeten la Constitución. Edificio en calle Huérfanos, centro."],
["Fiscalía Nacional (Ministerio Público)","Gobierno y justicia","Fiscalía Nacional Chile","Santiago","Sede nacional del Ministerio Público (los fiscales), en calle Catedral."],
["Contraloría General de la República","Gobierno y justicia","Contraloría General de la República","Santiago","Fiscaliza la legalidad de los actos del Estado. A pasos de La Moneda."],
["Cancillería (ex Hotel Carrera)","Gobierno y justicia","Ministerio de Relaciones Exteriores Chile","Santiago","Ministerio de Relaciones Exteriores, en el ex Hotel Carrera frente a la Plaza de la Constitución."],
["Banco Central de Chile","Gobierno y justicia","Banco Central de Chile","Santiago","En calle Agustinas, junto al Barrio Cívico."],
["Bolsa de Comercio","Gobierno y justicia","Bolsa de Comercio de Santiago","Santiago","Edificio histórico en la calle La Bolsa, centro."],
["Municipalidad de Santiago","Gobierno y justicia","Municipalidad de Santiago","Santiago","Edificio consistorial en la Plaza de Armas."],
["Corte de Apelaciones de San Miguel","Gobierno y justicia","Corte de Apelaciones de San Miguel","San Miguel","La otra Corte de Apelaciones de la región (cubre el sur de Santiago), en Gran Avenida."],
["Embajada de Estados Unidos","Gobierno y justicia","Embajada de los Estados Unidos en Chile","Las Condes","En Av. Andrés Bello, junto al Mapocho, frente al sector Costanera Center."],
["Escuela Militar","Gobierno y justicia","Escuela Militar del Libertador Bernardo O'Higgins","Las Condes","Escuela de oficiales del Ejército; da nombre a la estación de la L1."],
["Escuela de Carabineros","Gobierno y justicia","Escuela de Carabineros del General Carlos Ibáñez del Campo","Ñuñoa","Escuela de oficiales de Carabineros, en Av. Antonio Varas."],
["Escuela de Aviación","Gobierno y justicia","Escuela de Aviación Capitán Manuel Ávalos Prado","El Bosque","Escuela de oficiales de la FACh, junto a la Base Aérea El Bosque."],
["Ex Penitenciaría (Santiago 1)","Gobierno y justicia","Centro de Detención Preventiva Santiago 1","Santiago","Principal recinto penitenciario de la ciudad, en Av. Pedro Montt."],
// --- más lugares fuera del centro
["Hospital El Carmen","Salud","Hospital El Carmen Doctor Luis Valentín Ferrada","Maipú","Gran hospital público del poniente, en Camino a Rinconada."],
["Parque Laguna Carén","Cerros y parques","Laguna Carén","Pudahuel","Parque de la U. de Chile en torno a una laguna, junto a la Ruta 68."],
["ENEA (parque de negocios)","Malls y edificios","Enea Pudahuel","Pudahuel","Parque empresarial e industrial junto al aeropuerto."],
["Persa Teniente Cruz","Barrios","Persa Teniente Cruz","Pudahuel","Feria persa en Av. Teniente Cruz, sector poniente."],
["Museo Nacional Aeronáutico","Cultura","Museo Nacional Aeronáutico y del Espacio","Cerrillos","Aviones y espacio, en el ex aeródromo de Cerrillos."],
["Hospital Félix Bulnes","Salud","Hospital Clínico Félix Bulnes","Cerro Navia","Hospital del sector norponiente (nuevo edificio en Av. Mapocho)."],
["Cementerio Parque del Recuerdo","Cultura","Parque del Recuerdo","Huechuraba","Cementerio parque en Américo Vespucio Norte."],
["Hospital San José","Salud","Hospital San José, Independencia","Independencia","Hospital público del sector norte, en el barrio de hospitales."],
["Hospital Roberto del Río","Salud","Hospital Roberto del Río","Independencia","Hospital de niños del sector norte."],
["Mall Barrio Independencia","Malls y edificios","Mall Barrio Independencia","Independencia","Mall en Av. Independencia."],
["Cementerio Católico","Cultura","Cementerio Católico de Santiago","Recoleta","Cementerio histórico, vecino del Cementerio General."],
["Teatro Oriente","Cultura","Teatro Oriente","Providencia","Teatro y sala de conciertos en Av. Pedro de Valdivia con Providencia."],
["Hospital FACh","Salud","Hospital Clínico Fuerza Aérea de Chile","Las Condes","Hospital de la Fuerza Aérea en Av. Las Condes."],
["Edificio Titanium","Malls y edificios","Titanium La Portada","Las Condes","Rascacielos en Isidora Goyenechea, en Sanhattan."],
["Casa Piedra","Cultura","Casa Piedra","Vitacura","Centro de eventos junto al Mapocho, en San Josemaría Escrivá de Balaguer."],
["Farellones","Cerros y parques","Farellones","Lo Barnechea","Pueblo de montaña y centro de ski. Aunque está en la cordillera, es parte de la comuna de Lo Barnechea."],
["Valle Nevado","Cerros y parques","Valle Nevado","Lo Barnechea","Centro de ski, sobre Farellones."],
["Parque Aguas de Ramón","Cerros y parques","Parque Natural Aguas de Ramón","La Reina","Parque natural de precordillera, punto de partida de trekkings."],
["Teatro UC","Cultura","Teatro UC Jorge Washington","Ñuñoa","Teatro de la U. Católica, a pasos de Plaza Ñuñoa."],
["Villa Olímpica","Barrios","Villa Olímpica, Ñuñoa","Ñuñoa","Conjunto de departamentos junto al Estadio Nacional."],
["Mall Paseo Quilín","Malls y edificios","Mall Paseo Quilín","Peñalolén","Mall en Av. Quilín con Américo Vespucio."],
["Las Vizcachas","Barrios","Las Vizcachas, Puente Alto","Puente Alto","Sector junto al río Maipo, entrada al Cajón del Maipo."],
["Bajos de Mena","Barrios","Bajos de Mena","Puente Alto","Gran sector residencial del sur de Puente Alto."],
["Hospital Padre Hurtado","Salud","Hospital Padre Hurtado, San Ramón","San Ramón","Hospital público del sector sur, en calle Esperanza."],
["Hospital Barros Luco","Salud","Hospital Barros Luco Trudeau","San Miguel","Gran hospital público en Gran Avenida."],
["Mercado Lo Valledor","Barrios","Lo Valledor","Pedro Aguirre Cerda","Mercado mayorista de frutas y verduras del sur poniente."],
["Mall Plaza Sur","Malls y edificios","Mall Plaza Sur","San Bernardo","Mall en la Ruta 5 Sur, sector Nos."],
["Mall Paseo Estación","Malls y edificios","Mall Paseo Estación","Estación Central","Mall junto a la Estación Central."],
["Hospital Luis Calvo Mackenna","Salud","Hospital Luis Calvo Mackenna","Providencia","Hospital de niños en Av. Antonio Varas."],
["Hospital del Trabajador","Salud","Hospital del Trabajador ACHS","Providencia","Hospital de la ACHS en Ramón Carnicer, cerca de Plaza Italia."],
["Instituto Nacional del Tórax","Salud","Instituto Nacional del Tórax","Providencia","Hospital en el sector de José Manuel Infante / Salvador."],
["Estadio El Teniente? no","",null,null,null],
["Parque Juan XXIII","Cerros y parques","Parque Juan XXIII, Ñuñoa","Ñuñoa","Parque de barrio en Ñuñoa, entre Irarrázaval y Grecia."],
["Plaza Las Lilas? dup","",null,null,null],
["Mall Florida Center? dup","",null,null,null],
["Parque Cousiño Macul? no","",null,null,null],
["Viña Cousiño Macul","Cultura","Viña Cousiño Macul","Peñalolén","Viña histórica en Av. Quilín, al pie de la precordillera."],
["Viña Concha y Toro (Pirque)","Cultura","Viña Concha y Toro, Pirque","Pirque","Viña histórica en Pirque, al sur de Puente Alto."],
["Hospital Sótero? dup","",null,null,null],
["Universidad Católica Silva Henríquez? no","",null,null,null],
["Mall Arauco Quilicura","Malls y edificios","Mall Arauco Quilicura","Quilicura","Mall en Av. Américo Vespucio, al norte."],
["Plaza de Quilicura","Barrios","Plaza de Armas de Quilicura","Quilicura","Centro histórico de Quilicura."],
["Plaza de Renca","Barrios","Plaza de Armas de Renca","Renca","Centro de Renca, al pie del cerro."],
["Hospital de La Florida","Salud","Hospital Clínico Metropolitano La Florida","La Florida","Hospital público en Froilán Roa."],
["Parque Brasil","Cerros y parques","Parque Brasil, La Granja","La Granja","Parque en Av. Santa Rosa, sector sur."],
["Templo Mayor de los Mormones","Religión","Templo de Santiago Chile","Providencia","Templo de la Iglesia de Jesucristo de los Santos de los Últimos Días, en Av. Pocuro; es el único templo mormón de Santiago (el primero de Sudamérica hispana, de 1983)."],
// --- agregados 2: educación técnica y más universidades
["UTFSM – Campus San Joaquín","Universidades","Universidad Técnica Federico Santa María, San Joaquín","San Joaquín","Campus santiaguino de la U. Técnica Federico Santa María, en Av. Vicuña Mackenna (frente al Campus San Joaquín de la UC)."],
["UTFSM – Campus Vitacura","Universidades","Universidad Técnica Federico Santa María, Vitacura","Vitacura","Sede de la U. Santa María en Av. Santa María, junto al Mapocho."],
["Duoc UC – sede San Joaquín","Universidades","Duoc UC Sede San Joaquín","San Joaquín","Sede de Duoc UC en Av. Vicuña Mackenna, junto al Campus San Joaquín."],
["Duoc UC – sede Alameda","Universidades","Duoc UC Sede Alameda","Santiago","Sede de Duoc UC en el barrio universitario (Av. España con Alameda)."],
["Duoc UC – sede Padre Alonso de Ovalle","Universidades","Duoc UC Sede Padre Alonso de Ovalle","Santiago","Sede de Duoc UC en el centro, a pasos de la Alameda."],
["Duoc UC – sede Maipú","Universidades","Duoc UC Sede Maipú","Maipú","Sede de Duoc UC cerca de la Plaza de Maipú."],
["Duoc UC – sede Puente Alto","Universidades","Duoc UC Sede Puente Alto","Puente Alto","Sede de Duoc UC en Av. Concha y Toro."],
["INACAP Maipú","Universidades","INACAP Maipú","Maipú","Sede de INACAP en Av. Américo Vespucio, Maipú."],
["INACAP Renca","Universidades","INACAP Renca","Renca","Sede de INACAP en Renca (sector Panamericana)."],
["INACAP Puente Alto","Universidades","INACAP Puente Alto","Puente Alto","Sede de INACAP en Av. Concha y Toro."],
["AIEP – sede Bellavista","Universidades","AIEP Bellavista","Providencia","Instituto profesional AIEP (de la U. Andrés Bello), en el barrio Bellavista."],
["Universidad Bernardo O'Higgins","Universidades","Universidad Bernardo O'Higgins","Santiago","Universidad privada junto al Parque O'Higgins (Av. Viel)."],
["Universidad Católica Silva Henríquez","Universidades","Universidad Católica Silva Henríquez","Santiago","Universidad salesiana en General Jofré, cerca de Vicuña Mackenna con la Alameda."],
["Universidad de las Américas (campus Providencia)","Universidades","Universidad de Las Américas Campus Providencia","Providencia","Campus de la UDLA en Av. Manuel Montt / Antonio Varas."],
["Universidad Academia de Humanismo Cristiano","Universidades","Universidad Academia de Humanismo Cristiano","Providencia","Universidad en Av. Condell, Providencia."],
["U. de Chile – FAU (Arquitectura)","Universidades","Facultad de Arquitectura y Urbanismo Universidad de Chile","Santiago","Facultad de Arquitectura y Urbanismo, en Av. Portugal, a pasos de la Alameda."],
["UAI – sede Presidente Errázuriz","Universidades","Universidad Adolfo Ibáñez, Presidente Errázuriz","Las Condes","Sede de postgrados de la UAI, en Av. Presidente Errázuriz."],
// --- barrios y sectores
["Plaza San Enrique","Barrios","Plaza San Enrique, Lo Barnechea","Lo Barnechea","Plaza al final de Av. Las Condes, donde parte el camino a Farellones y el camino a El Arrayán. Zona de restaurantes y bares."],
["El Arrayán","Barrios","El Arrayán, Lo Barnechea","Lo Barnechea","Sector precordillerano siguiendo el estero Arrayán hacia el norte desde Plaza San Enrique; casas, restaurantes y el Santuario de la Naturaleza."],
["La Dehesa (sector)","Barrios","La Dehesa, Lo Barnechea","Lo Barnechea","El gran sector residencial de Lo Barnechea en torno a Av. La Dehesa y El Rodeo: malls, colegios y clubes."],
["San Carlos de Apoquindo (sector)","Barrios","San Carlos de Apoquindo, Las Condes","Las Condes","Sector alto de Las Condes: U. de los Andes, UDD, estadio de la UC, colegios."],
["Santa María de Manquehue","Barrios","Santa María de Manquehue","Vitacura","Barrio residencial al pie del cerro Manquehue; colegios San Benito, Huelén, SSCC Manquehue."],
["Lo Curro","Barrios","Lo Curro, Vitacura","Vitacura","Barrio residencial en los cerros del norte de Vitacura, sobre el Mapocho."],
["Jardín del Este","Barrios","Jardín del Este, Vitacura","Vitacura","Barrio residencial clásico de Vitacura, entre Av. Vitacura y Kennedy."],
["La Legua","Barrios","La Legua, San Joaquín","San Joaquín","Población histórica de San Joaquín (Legua Vieja, Nueva y Emergencia), al oriente de Av. Santa Rosa."],
["Lo Ovalle (sector)","Barrios","Avenida Lo Ovalle, San Miguel","San Miguel","Sector en torno a Gran Avenida con Av. Lo Ovalle (paradero 18): límite San Miguel–La Cisterna, estación Lo Ovalle (L2) e intermodal."],
["La Victoria","Barrios","La Victoria, Pedro Aguirre Cerda","Pedro Aguirre Cerda","Población emblemática nacida de una toma en 1957, en Pedro Aguirre Cerda."],
["La Pincoya","Barrios","La Pincoya, Huechuraba","Huechuraba","Población histórica en el norte de Huechuraba, al pie de los cerros."],
["La Bandera","Barrios","La Bandera, San Ramón","San Ramón","Población de San Ramón, junto al Parque La Bandera."],
["Lo Hermida","Barrios","Lo Hermida, Peñalolén","Peñalolén","Sector popular de Peñalolén, entre Av. Grecia y Los Presidentes."],
["Villa Francia","Barrios","Villa Francia, Estación Central","Estación Central","Población de Estación Central, en Av. 5 de Abril."],
["Villa Frei","Barrios","Villa Frei, Ñuñoa","Ñuñoa","Conjunto habitacional moderno de los años 60 en Ñuñoa, junto a Av. Irarrázaval con Ramón Cruz (estación Villa Frei, L3)."],
["El Llano Subercaseaux","Barrios","El Llano Subercaseaux, San Miguel","San Miguel","El barrio de edificios de San Miguel a lo largo de Gran Avenida (estación El Llano, L2)."],
["Población José María Caro","Barrios","Población José María Caro, Lo Espejo","Lo Espejo","Gran población del sur de Santiago, en Lo Espejo."],
["Barrio Concha y Toro","Barrios","Barrio Concha y Toro, Santiago","Santiago","Pequeño barrio patrimonial de calles curvas junto a la Alameda, entre Brasil y Cumming."],
["Barrio París-Londres","Barrios","Barrio París-Londres","Santiago","Dos calles adoquinadas de estilo europeo detrás de la Iglesia de San Francisco, en la Alameda."],
["Villa Portales","Barrios","Villa Portales, Estación Central","Estación Central","Conjunto de bloques modernistas junto a la USACH y la Quinta Normal."],
["Lo Cañas","Barrios","Lo Cañas, La Florida","La Florida","Sector precordillerano de La Florida, de parcelas y condominios."],
["Los Trapenses","Barrios","Los Trapenses, Lo Barnechea","Lo Barnechea","Sector residencial del norte de Lo Barnechea, en torno al Camino Los Trapenses (colegios, Santiago College)."],
["San Damián","Barrios","San Damián, Las Condes","Las Condes","Barrio residencial del sector alto de Las Condes, entre Av. Las Condes y los cerros, en el límite con Vitacura y Lo Barnechea; cerca de la Clínica Las Condes y el Colegio Los Andes."],
["Quinchamalí","Barrios","Quinchamalí, Las Condes","Las Condes","Barrio residencial al final de Av. Las Condes, al pie de los cerros, justo antes de Plaza San Enrique y el límite con Lo Barnechea."],
["AudioMusica (Chile España)","Malls y edificios","Audiomusica, Chile España","Ñuñoa","La tienda de instrumentos musicales, en Av. Chile España."],
["Parque Almagro","Cerros y parques","Parque Almagro, Santiago","Santiago","Parque alargado al sur de la Alameda, entre San Diego y Lord Cochrane: Iglesia de los Sacramentinos, U. Central (estación Parque Almagro, L3)."],
["El Cruceral (Pirque)","Barrios","El Cruceral, Pirque","Pirque","Cruce y caserío en la entrada de Pirque, apenas se cruza el río Maipo viniendo de Puente Alto."],
["Disquería Funtracks","Malls y edificios","Funtracks","Providencia","Tienda de discos en Nueva de Lyon, en el corazón comercial de Providencia."],
["MUT (Mercado Urbano Tobalaba)","Malls y edificios","Mercado Urbano Tobalaba","Las Condes","Mercado, tiendas y oficinas sobre la estación Tobalaba, en Apoquindo con Tobalaba, frente a Costanera Center."],
["Lynch (La Reina)","Barrios","Lynch, La Reina","La Reina","Sector residencial de La Reina en torno a las avenidas Lynch Norte y Lynch Sur, entre Echeñique / Príncipe de Gales y Larraín."],
["Feria del domingo de José Arrieta","Barrios","Avenida José Arrieta, Peñalolén","Peñalolén","Feria libre que se instala los domingos en Av. José Arrieta, en el límite entre La Reina y Peñalolén."],
["Catedral Metropolitana","Religión","Catedral Metropolitana de Santiago, Plaza de Armas","Santiago","La catedral católica de Santiago, en el costado poniente de la Plaza de Armas; sede del arzobispado."],
["Sinagoga Bicur Joilim","Religión","Sinagoga Bicur Joilim","Santiago","La sinagoga histórica de la comunidad judía de Santiago, en Av. Matta."],
["Mezquita As-Salam","Religión","Mezquita As-Salam","Ñuñoa","La principal mezquita de Santiago, en Campoamor con Chile España."],
["Catedral Evangélica de Chile","Religión","Catedral Evangélica de Chile","Estación Central","Templo de la Iglesia Metodista Pentecostal (\"Jotabeche\"), en la Alameda; el principal templo evangélico del país, donde se celebra el Te Deum evangélico."],
["Teleférico del San Cristóbal (estación Oasis)","Transporte","Teleférico de Santiago","Providencia","Estación baja del teleférico del Parque Metropolitano, en Av. El Cerro (Pedro de Valdivia Norte). Sube al cerro San Cristóbal pasando por Tupahue hasta la Cumbre."],
["Teleférico Bicentenario (estación Canal San Carlos)","Transporte","Teleférico Bicentenario","Las Condes","Teleférico en construcción que unirá el sector de Tobalaba / Costanera Center con Ciudad Empresarial (Huechuraba), pasando sobre el cerro San Cristóbal. Esta es su estación sur, junto a la desembocadura del Canal San Carlos."],
["Quebrada de Macul","Cerros y parques","Parque Natural Quebrada de Macul","Peñalolén","Parque natural de precordillera al final de Diagonal Las Torres, pasada la U. Adolfo Ibáñez; trekking con cascadas. La quebrada marca el límite entre Peñalolén y La Florida, y por ella bajó el aluvión de 1993."],
];
