// [display name, regex on OSM name, hint]
module.exports=[
["Alameda (Av. Libertador Bernardo O'Higgins)","^Avenida Libertador Bernardo O.Higgins$","El eje principal de la ciudad: oriente–poniente desde Plaza Italia, por el centro y Estación Central, hacia el poniente. Bajo ella va la Línea 1."],
["Av. Providencia","^Avenida Providencia$","Continúa la Alameda hacia el oriente desde Plaza Italia hasta Tobalaba (sentido poniente)."],
["Av. Nueva Providencia","^Avenida Nueva Providencia$","Par vial de Providencia (sentido oriente), entre Plaza Italia y Los Leones."],
["Av. Apoquindo","^Avenida Apoquindo$","Continuación de Providencia en Las Condes: El Golf, Escuela Militar, Manquehue, hasta Los Dominicos. Bajo ella va la L1."],
["Av. Las Condes","^Avenida Las Condes$","Diagonal desde Apoquindo hacia el nororiente: Estoril, Padre Hurtado, hasta el Puente San Enrique en Lo Barnechea."],
["Av. Presidente Kennedy","^Avenida Presidente Kennedy( Lateral)?$","Eje oriente–poniente al norte de Apoquindo: Parque Arauco, Alto Las Condes. Junto a ella corre la Costanera Norte."],
["Av. Vitacura","^Avenida Vitacura$","Eje de Vitacura paralelo al Mapocho: desde Providencia (Costanera Center) hacia el nororiente."],
["Av. Andrés Bello","^Avenida Andrés Bello$","Ribera sur del Mapocho en Providencia; pasa frente a Costanera Center."],
["Av. Santa María","^Avenida Santa María$","Ribera norte del Mapocho, de Recoleta/Providencia a Vitacura (Bellavista, Pedro de Valdivia Norte)."],
["Costanera Norte","^(Autopista |Avenida )?Costanera Norte$","Autopista urbana junto/bajo el Mapocho, desde Lo Barnechea / Kennedy hasta el Aeropuerto."],
["Américo Vespucio","Vespucio","El anillo que rodea la ciudad. Por el oriente pasa por Vitacura, Las Condes, Ñuñoa, Peñalolén y La Florida; por el poniente por Maipú y Pudahuel."],
["Av. Tobalaba","^Avenida Tobalaba$","Norte–sur junto al Canal San Carlos: desde Providencia/Las Condes, separa Ñuñoa de La Reina y sigue a Peñalolén."],
["Av. Cristóbal Colón","^Avenida Cristóbal Colón$","Oriente–poniente en Las Condes, desde Tobalaba hacia el oriente alto."],
["Av. Francisco Bilbao","^Avenida Francisco Bilbao$","Oriente–poniente: separa Providencia de Ñuñoa y Las Condes de La Reina."],
["Av. Irarrázaval","^Avenida Irarrázaval$","Eje principal de Ñuñoa: Plaza Ñuñoa hasta Plaza Egaña. Bajo ella va la L3."],
["Av. Grecia","^Avenida Grecia$","Oriente–poniente por Ñuñoa y Peñalolén; pasa junto al Estadio Nacional."],
["Av. José Pedro Alessandri","^Avenida José Pedro Alessandri$","Norte–sur por Ñuñoa y Macul: Pedagógico (UMCE), UTEM, Campus Juan Gómez Millas (U. de Chile)."],
["Av. Ossa","^Avenida Ossa$","Norte–sur en el límite Ñuñoa–La Reina–Peñalolén, al sur de Plaza Egaña (trazado de Vespucio)."],
["Av. Príncipe de Gales","^Avenida Príncipe de Gales$","Oriente–poniente por La Reina, desde Plaza Egaña al oriente."],
["Av. Larraín","^Avenida Larraín$","Oriente–poniente en La Reina, al sur de Príncipe de Gales."],
["Av. Padre Hurtado","^Avenida Padre Hurtado( Norte| Sur| Central)?$","Norte–sur en Vitacura y Las Condes, desde el Mapocho hacia el sur hasta Bilbao."],
["Av. Manquehue","^Avenida Manquehue( Norte| Sur)?$","Norte–sur en Vitacura y Las Condes; cruza Apoquindo en la estación Manquehue."],
["Av. Alonso de Córdova","Alonso de Córdova","Vitacura/Las Condes: calle de tiendas y restaurantes."],
["Av. Nueva Costanera","Nueva Costanera","Vitacura: restaurantes y tiendas, paralela a Av. Vitacura."],
["Av. Luis Pasteur","Luis Pasteur","Vitacura: une Av. Vitacura con el sector alto (Santa María de Manquehue / Lo Curro)."],
["Av. Monseñor Escrivá de Balaguer","Escrivá de Balaguer","Vitacura: ribera sur del Mapocho, junto al Parque Bicentenario y hacia el oriente."],
["Av. La Dehesa","^Avenida La Dehesa$","Eje norte–sur de La Dehesa (Lo Barnechea): Portal La Dehesa, colegios del sector."],
["Av. Raúl Labbé","Raúl Labbé","Lo Barnechea: une La Dehesa con Las Condes; continúa hacia Farellones."],
["Av. José Alcalde Délano","Alcalde Délano","Lo Barnechea: une La Dehesa con Av. Las Condes por el oriente."],
["Camino El Alba","^Camino El Alba$","Las Condes: oriente–poniente en el sector oriente alto, hacia San Carlos de Apoquindo."],
["Av. Paul Harris","Paul Harris","Las Condes: norte–sur en el sector oriente alto (Los Dominicos)."],
["Av. Tomás Moro","Tomás Moro","Las Condes: norte–sur entre Apoquindo y Bilbao."],
["Av. San Carlos de Apoquindo","San Carlos de Apoquindo","Las Condes: sube al sector de San Carlos de Apoquindo (U. de los Andes, UDD, estadio de la UC)."],
["Av. Pedro de Valdivia","^Avenida Pedro de Valdivia$","Norte–sur por Providencia y Ñuñoa; cruza Providencia en la estación Pedro de Valdivia."],
["Av. Los Leones","^Avenida Los Leones$","Norte–sur por Providencia y Ñuñoa, desde Providencia hacia el sur."],
["Av. Antonio Varas","^(Avenida )?Antonio Varas$","Providencia/Ñuñoa: norte–sur entre Providencia e Irarrázaval."],
["Av. Manuel Montt","^(Avenida )?Manuel Montt$","Providencia/Ñuñoa: norte–sur; estación Manuel Montt de la L1."],
["Av. Eliodoro Yáñez","Eliodoro Yáñez","Providencia: oriente–poniente al sur de Av. Providencia, hasta Tobalaba."],
["Av. Pocuro","^Avenida Pocuro$","Providencia: oriente–poniente con ciclovía, hasta Tobalaba."],
["Av. Diagonal Oriente","^Diagonal Oriente$|^Doctor Pedro Lautaro Ferrer$|^Avenida Jaime Guzmán Errázuriz$|^Avenida Presidente José Batlle y Ordóñez$","Diagonal que cruza el límite Providencia–Ñuñoa de norponiente a suroriente, desde Antonio Varas hasta Plaza Egaña. Va cambiando de nombre: Diagonal Oriente, Pedro Lautaro Ferrer, Jaime Guzmán Errázuriz (Campus Oriente UC), José Batlle y Ordóñez y de nuevo Diagonal Oriente.",[-70.595,-33.447],{bt:1,gap:1.5,trMin:0.5}],
["Av. Mariano Sánchez Fontecilla","Sánchez Fontecilla","Corre junto al Canal San Carlos por el lado oriente, frente a Av. Tobalaba (que va por el lado poniente), desde Las Condes hacia el sur por La Reina, Peñalolén y La Florida. Está cortada en varios tramos.",[-70.590,-33.427],{gap:3.5}],
["Av. José Arrieta","José Arrieta","Peñalolén/La Reina: oriente–poniente hacia la precordillera."],
["Av. Vicuña Mackenna","Vicuña Mackenna","Norte–sur desde Plaza Italia hasta Puente Alto: Ñuñoa, San Joaquín (Campus UC), Macul, La Florida. L5 y L4 van por tramos de ella."],
["Av. Macul","^Avenida Macul$","Norte–sur por Macul y La Florida, desde Irarrázaval al sur."],
["Av. Departamental","^Avenida Departamental$","Oriente–poniente en el sur: de La Florida/Peñalolén a Lo Espejo, pasando por Macul, San Joaquín y San Miguel."],
["Av. Quilín","^Avenida Quilín$","Oriente–poniente por Macul y Peñalolén."],
["Av. Rodrigo de Araya","Rodrigo de Araya","Oriente–poniente por Ñuñoa, Macul y San Joaquín."],
["Av. Santa Rosa","^Avenida Santa Rosa$","Norte–sur desde la Alameda hacia el sur: Santiago, San Joaquín, La Granja, La Pintana."],
["Gran Avenida (José Miguel Carrera)","Gran Avenida","Norte–sur por San Miguel, La Cisterna, El Bosque y San Bernardo. Bajo ella va la L2."],
["Av. Matta (Manuel Antonio Matta)","^Avenida Manuel Antonio Matta$","Oriente–poniente en el sur de Santiago Centro (estación Matta, Parque Almagro hacia el sur).",[-70.645,-33.4565]],
["Av. General Bustamante","General Bustamante","Junto al Parque Bustamante, desde Plaza Italia al sur."],
["Av. Recoleta","^Avenida Recoleta$","Norte–sur en Recoleta y Huechuraba, desde La Vega hacia el norte. Bajo ella va la L2."],
["Av. Independencia","^Avenida Independencia$","Norte–sur en Independencia y Conchalí: hospitales, Campus Norte U. de Chile. Bajo ella va la L3."],
["Av. Matucana","^(Avenida )?Matucana$","Norte–sur en Santiago poniente / Quinta Normal: Matucana 100, Parque Quinta Normal."],
["Av. Mapocho","^Avenida Mapocho$","Oriente–poniente al norte de la Alameda hacia Quinta Normal y Cerro Navia."],
["Av. San Pablo","^(Avenida )?San Pablo$","Oriente–poniente desde Santiago Centro hacia Lo Prado y Pudahuel."],
["Av. Pajaritos","Pajaritos","Estación Central/Maipú: une la Alameda con Plaza de Maipú."],
["Av. General Velásquez","^(Avenida )?General Velásquez$|^Avenida Joaquín Walker Martínez$|^Avenida Padre Alberto Hurtado$","Eje norte–sur del poniente que va cambiando de nombre: Joaquín Walker Martínez en Quinta Normal, General Velásquez por Estación Central y Cerrillos, y Padre Alberto Hurtado más al sur. Junto a ella corre un tramo de la Autopista Central.",[-70.690,-33.47],{bt:1}],
["Autopista Central","Autopista Central","Ruta 5 a través de la ciudad, de norte a sur."],
["Autopista del Sol (Ruta 78)","^Ruta 78$","Autopista hacia San Antonio; sale por el surponiente (Santiago, Cerrillos, Maipú)."],
["Ruta 68 (a Valparaíso)","^Ruta 68$","Autopista hacia Valparaíso / Viña; sale por el poniente (Pudahuel, cerca del aeropuerto)."],
["Av. La Florida","^Avenida La Florida$","Norte–sur por La Florida y Puente Alto."],
["Av. Concha y Toro","Concha y Toro","Puente Alto: continuación de Vicuña Mackenna hacia el sur, hasta la plaza de Puente Alto."],
["Av. Dorsal","^Avenida Dorsal$","Norte: Conchalí y Recoleta, oriente–poniente."],
["Av. El Salto","^Avenida El Salto$","Recoleta/Huechuraba: norte–sur hacia Ciudad Empresarial."],
["Av. Las Rejas","Las Rejas","Estación Central / Lo Prado / Cerrillos: norte–sur."],
["Av. Carlos Valdovinos","Carlos Valdovinos","Oriente–poniente por San Joaquín y Pedro Aguirre Cerda (L5)."],
["Av. Presidente Balmaceda","Presidente Balmaceda","Santiago: ribera sur del Mapocho, al poniente de Cal y Canto."],
["Av. Ricardo Lyon","Ricardo Lyon","Providencia/Ñuñoa: norte–sur entre Providencia y Bilbao."],
["Av. Simón Bolívar","^Avenida Simón Bolívar$","Ñuñoa/La Reina: oriente–poniente."],
["Av. Marathon","Marathon","Ñuñoa/Macul: norte–sur por el poniente del Estadio Nacional."],
["Av. El Rodeo","^Avenida El Rodeo$","Lo Barnechea: sector El Rodeo / La Dehesa alta."],
["Av. Pintor Benito Rebolledo","Benito Rebolledo","Oriente–poniente en Macul / San Joaquín, en el sector del Campus San Joaquín UC."],
// --- agregadas (se extraen de btiles/): [nombre, regex, pista, ancla [lon,lat] o null, {kind, key}]
["Av. Presidente Riesco","^Avenida Presidente Riesco$","Las Condes: paralela a Apoquindo por el norte; pasa por El Golf, el Club de Golf Los Leones y el Parque Araucano.",null,{bt:1}],
["Av. Presidente Sebastián Piñera Echenique","Sebastián Piñera Echenique","Las Condes: la diagonal que va desde Apoquindo (sector Manquehue) hacia el suroriente hasta Bilbao con Padre Hurtado. Es la ex Av. IV Centenario, renombrada.",null,{bt:1}],
["General Blanche","^General Blanche$","Las Condes: oriente–poniente en el sector alto, sube hacia San Carlos de Apoquindo (U. de los Andes).",null,{bt:1}],
["Isidora Goyenechea","^Isidora Goyenechea$","Las Condes: la calle principal de El Golf / Sanhattan (restaurantes, Titanium al fondo).",null,{bt:1}],
["Av. Suecia","^Avenida Suecia$","Providencia/Ñuñoa: norte–sur, desde el Mapocho hacia Irarrázaval.",null,{bt:1}],
["Los Conquistadores","^Los Conquistadores$","Providencia: Pedro de Valdivia Norte, al pie del cerro San Cristóbal.",[-70.623,-33.425],{bt:1}],
["Av. Salvador","^Avenida Salvador$","Providencia/Ñuñoa: norte–sur desde Av. Providencia (Hospital del Salvador) hacia el sur; borde oriente del Barrio Italia.",null,{bt:1}],
["Av. Beauchef","^Avenida Beaucheff?$","Santiago: borde poniente del Parque O'Higgins; Facultad de Ingeniería de la U. de Chile.",null,{bt:1}],
["Av. Pedro Montt","^(Avenida )?Pedro Montt$","Santiago: al sur del Parque O'Higgins; Centro de Justicia y ex Penitenciaría.",[-70.659,-33.473],{bt:1}],
["Bascuñán Guerrero","^Bascuñán Guerrero$","Santiago / Estación Central: norte–sur desde la Alameda (Barrio Meiggs) hacia el sur.",null,{bt:1}],
["Av. Blanco Encalada","^Avenida Almirante Blanco Encalada$","Santiago: oriente–poniente al sur de la Alameda; Club Hípico, Beauchef, límite sur del Barrio República.",null,{bt:1}],
["Las Hualtatas","^Las Hualtatas$","Vitacura: oriente–poniente en el sector alto (Tabancura, colegios).",null,{bt:1}],
["Av. Chile España","^Avenida Chile España$","Ñuñoa: norte–sur corta, al norte de Irarrázaval (estación Chile España, L3).",null,{bt:1}],
["Dublé Almeyda","^Dublé Almeyda$","Ñuñoa: oriente–poniente, paralela a Irarrázaval por el sur.",null,{bt:1}],
["Av. Echeñique","^Avenida Echeñique$","La Reina / Ñuñoa: oriente–poniente, paralela a Príncipe de Gales.",null,{bt:1}],
["Av. Trinidad","^Avenida Trinidad( Oriente)?$","La Florida: oriente–poniente en el sur de la comuna (estación Trinidad, L4).",null,{bt:1}],
["Av. San José de la Estrella","^Avenida San José de La Estrella$","La Florida: oriente–poniente, al sur de Trinidad (estación San José de la Estrella, L4).",null,{bt:1}],
["Av. Diez de Julio","^Avenida Diez de Julio Huamachuco$","Santiago: oriente–poniente, la calle de los repuestos de autos, entre Vicuña Mackenna y la Autopista Central.",null,{bt:1}],
["Luis Thayer Ojeda","^Luis Thayer Ojeda$","Providencia: norte–sur corta, desde Av. Providencia (sector Costanera Center / Tobalaba) hacia Bilbao.",null,{bt:1}],
["Av. Holanda","^Avenida Holanda$","Providencia/Ñuñoa: norte–sur entre Providencia e Irarrázaval.",null,{bt:1}],
["Autopista Nororiente (Radial Nororiente)","^Autopista Nororiente$","Autopista concesionada (la Radial Nororiente): une Vitacura / La Pirámide con Chicureo y Colina por túneles bajo el cordón del Manquehue.",null,{bt:1,kind:"autopista"}],
["Autopista Los Libertadores (Ruta 57)","^Autopista Los Libertadores$","Sale hacia el norte por Quilicura / Colina rumbo a Los Andes y el paso a Mendoza.",null,{bt:1,kind:"autopista"}],
["Autopista Acceso Sur","^Autopista Acceso Sur$","Entrada/salida sur alternativa a la Ruta 5: desde Vespucio Sur por La Pintana y Puente Alto hasta empalmar con la Ruta 5 al sur.",null,{bt:1,kind:"autopista"}],
["Ruta 5 Norte (Panamericana)","^Ruta 5 Norte$","La Panamericana hacia el norte (Lampa, Tiltil, La Serena).",null,{bt:1,kind:"autopista"}],
["Camino a Farellones (G-21)","^Camino a Farellones$","Desde Lo Barnechea sube a Farellones, El Colorado, La Parva y Valle Nevado.",null,{bt:1,kind:"autopista"}],
["Camino al Volcán (G-25)","^Camino al Volcán$","Desde Puente Alto / Las Vizcachas entra al Cajón del Maipo.",null,{bt:1,kind:"autopista"}],
["Río Mapocho","^Río Mapocho$","El río de Santiago: baja de la cordillera por Lo Barnechea, Vitacura, Providencia y el centro, y sigue al poniente hasta el Maipo.",null,{bt:1,kind:"agua",key:"waterway"}],
["Río Maipo","^Río Maipo$","El gran río de la región: baja por el Cajón del Maipo y bordea Puente Alto, Pirque y San Bernardo por el sur.",null,{bt:1,kind:"agua",key:"waterway"}],
["Canal San Carlos","^Canal San Carlos$","Canal que lleva agua del Maipo al Mapocho: corre de sur a norte junto a Av. Tobalaba y desemboca frente al MUT / Costanera Center.",null,{bt:1,kind:"agua",key:"waterway"}],
["Zanjón de la Aguada","^Zanjón de la Aguada$","Cauce que cruza el sur de la ciudad de oriente a poniente (Macul, San Joaquín, Santiago, Cerrillos, Maipú).",null,{bt:1,kind:"agua",key:"waterway"}],
["Canal Las Perdices","^Canal (de )?Las Perdices$","Canal de riego al pie de la precordillera: La Reina, Peñalolén, La Florida.",null,{bt:1,kind:"agua",key:"waterway"}],
["Canal El Carmen","^Canal El Carmen$","Canal que sale del San Carlos y bordea el cerro San Cristóbal hacia Huechuraba y el norte.",null,{bt:1,kind:"agua",key:"waterway"}],
["Camino San Francisco de Asís","^Camino San Francisco de Asís$","Las Condes / Vitacura: sube desde Av. Las Condes por el sector San Damián hacia los cerros (Colegio Los Andes, Clínica Las Condes cerca).",null,{bt:1}],
["Av. Santa Isabel","^Avenida Santa Isabel$","Santiago / Providencia: oriente–poniente al sur de la Alameda, desde Vicuña Mackenna (Barrio Italia) hacia el centro sur.",null,{bt:1}],
["Ñuble","^Ñuble$","Santiago: oriente–poniente al sur de Av. Matta, entre Vicuña Mackenna y la Autopista Central (estación Ñuble).",null,{bt:1}],
["Franklin","^Franklin$","Santiago: oriente–poniente, la calle del Barrio Franklin y los persas.",null,{bt:1}],
["Moneda","^Moneda$","Santiago Centro: oriente–poniente, pasa por el frente norte de La Moneda, una cuadra al norte de la Alameda.",null,{bt:1}],
["Av. Presidente Salvador Allende Gossens","^Avenida Presidente Salvador Allende Gossens$|^Avenida Salesianos$","San Miguel / San Joaquín: oriente–poniente, entre Carlos Valdovinos y Departamental. Su tramo oriente conserva el nombre antiguo, Salesianos.",[-70.650,-33.490],{bt:1}],
["Av. Ecuador","^Avenida Ecuador$","Estación Central: oriente–poniente al norte de la Alameda, junto a la USACH (estación Ecuador de la L1 queda en la Alameda).",null,{bt:1}],
["Av. 5 de Abril","^(Avenida )?5 de Abril$","Estación Central / Maipú: sale de la Alameda hacia el surponiente y llega a la Plaza de Maipú.",[-70.722,-33.473],{bt:1}],
["Av. Portales","^Avenida Portales$","Santiago / Quinta Normal: oriente–poniente, borde norte del Parque Quinta Normal y del barrio Yungay.",[-70.684,-33.4445],{bt:1}],
["Av. Las Industrias","^Avenida Las Industrias$","San Joaquín / La Granja: norte–sur, paralela a Santa Rosa por el oriente.",[-70.623,-33.524],{bt:1}],
["Ureta Cox","^Ureta Cox$","San Miguel / San Joaquín: oriente–poniente, entre Gran Avenida y Vicuña Mackenna.",null,{bt:1}],
["Gerónimo de Alderete","^Gerónimo de Alderete$","Vitacura / Las Condes: norte–sur corta, entre Av. Vitacura y Av. Las Condes (sector Estoril).",[-70.556,-33.392],{bt:1}],
["Av. Juan XXIII","^Avenida Juan XXIII$","Vitacura: une la Rotonda Irene Frei (Vitacura con Manquehue) con la Rotonda Carol Urzúa y el puente Lo Curro.",null,{bt:1}],
["Los Militares","^Los Militares$","Las Condes: paralela a Apoquindo por el norte, desde Escuela Militar hacia Manquehue (Parque Araucano).",null,{bt:1}],
["Las Tranqueras","^Las Tranqueras$","Vitacura / Las Condes: norte–sur en el sector oriente, entre Av. Vitacura y Av. Las Condes.",[-70.556,-33.390],{bt:1}],
["Martín de Zamora","^Martín de Zamora$","Las Condes: oriente–poniente, paralela a Colón por el norte, desde Tobalaba hacia Manquehue.",null,{bt:1}],
["Av. Charles Hamilton","^(Avenida )?Charles Hamilton$","Las Condes: sube desde Av. Las Condes (sector Estoril) hacia San Damián y San Carlos de Apoquindo.",null,{bt:1}],
["Av. José Manuel Infante","^Avenida José Manuel Infante$","Providencia / Ñuñoa: norte–sur, entre Av. Providencia e Irarrázaval.",null,{bt:1}],
["Av. Eduardo Castillo Velasco","^Alcalde Eduardo Castillo Velasco$","Ñuñoa: oriente–poniente, paralela a Irarrázaval por el sur (entre Dublé Almeyda y Grecia).",null,{bt:1}],
["Av. Pedro Fontova","^Avenida Pedro Fontova$","Huechuraba / Conchalí: norte–sur, sube desde Américo Vespucio hacia el sector norte de Huechuraba (Pedro Fontova, El Carmen).",null,{bt:1}],
["Av. Los Presidentes","^Avenida Los Presidentes$","Peñalolén: oriente–poniente, desde Américo Vespucio (estación Los Presidentes, L4) hacia la precordillera.",null,{bt:1}],
["Av. Sucre","^Avenida Sucre$","Ñuñoa: oriente–poniente, paralela a Irarrázaval por el norte, desde el Barrio Italia hacia Pedro de Valdivia.",null,{bt:1}],
["Pío Nono","^Pío Nono$","La calle principal del barrio Bellavista: va del puente frente a Plaza Italia hasta la entrada del cerro San Cristóbal (funicular y zoológico). Separa Recoleta de Providencia.",null,{bt:1}],
["Av. Carrascal","^Avenida Carrascal$","Quinta Normal / Cerro Navia: oriente–poniente por el norponiente, paralela al Mapocho por el sur.",null,{bt:1}],
["Av. Neptuno","^(Avenida )?Neptuno$","Lo Prado / Quinta Normal / Cerro Navia: norte–sur por el poniente; estación Neptuno de la L1.",[-70.723,-33.443],{bt:1}],
["Av. Bicentenario","^Avenida Bicentenario$","Vitacura: bordea el Parque Bicentenario por el lado del río Mapocho, frente a la Municipalidad de Vitacura.",null,{bt:1}],
["Av. Chesterton","^Avenida Chesterton$","Las Condes: norte–sur corta en el sector oriente, entre Av. Las Condes y Apoquindo / Camino El Alba (sector Los Dominicos).",null,{bt:1}],
["Av. Manuel Rodríguez","^Avenida Manuel Rodríguez (Norte|Sur)$","Santiago Centro: las calles laterales de la Autopista Central (la Norte-Sur). Manuel Rodríguez Norte va al norte de la Alameda y Manuel Rodríguez Sur al sur; separa el Barrio Brasil y República del centro.",null,{bt:1,trMin:0.5}],
["Av. Ricardo Cumming","^Avenida Ricardo Cumming$","Santiago: norte–sur entre la Alameda y el Mapocho; separa los barrios Brasil y Yungay (estación Cumming, L5).",null,{bt:1}],
["Exposición","^Exposición$","Estación Central / Santiago: norte–sur al costado oriente de la Estación Central, desde la Alameda hacia el sur; borde del Barrio Meiggs.",null,{bt:1}],
["Av. Pedro Aguirre Cerda","^Avenida Pedro Aguirre Cerda$","Cerrillos / Estación Central / Maipú: el antiguo Camino a Melipilla; sale hacia el surponiente junto al ex aeródromo de Cerrillos.",[-70.694,-33.481],{bt:1}],
["Camino a Melipilla","^Camino a Melipilla$","Maipú: continuación de Av. Pedro Aguirre Cerda hacia el surponiente, rumbo a Padre Hurtado y Melipilla.",null,{bt:1}],
["Paseo Ahumada","^Ahumada$","Santiago Centro: la peatonal comercial más conocida, de la Alameda a la Plaza de Armas.",[-70.6505,-33.440],{bt:1}],
["Paseo Estado","^Estado$","Santiago Centro: peatonal paralela a Ahumada, de la Alameda a la Plaza de Armas.",[-70.649,-33.440],{bt:1}],
["Bandera","^Bandera$","Santiago Centro: norte–sur, una cuadra al poniente de Ahumada; bancos, Tribunales, ex Congreso y el Paseo Bandera.",[-70.652,-33.440],{bt:1}],
["Compañía de Jesús","^Compañía de Jesús$","Santiago Centro: oriente–poniente, pasa por el costado sur de la Catedral y la Plaza de Armas y sigue hacia el Barrio Brasil.",null,{bt:1}],
["Teatinos","^Teatinos$","Santiago Centro: norte–sur, pasa por el costado poniente de La Moneda (ministerios).",null,{bt:1}],
["Morandé","^Morandé$","Santiago Centro: norte–sur, pasa por el costado oriente de La Moneda (Morandé 80) y la Plaza de la Constitución.",null,{bt:1}],
["Merced","^Merced$","Santiago Centro: oriente–poniente, de la Plaza de Armas hacia Lastarria y Bellas Artes, hasta cerca de Plaza Italia.",[-70.645,-33.437],{bt:1}],
["Catedral","^Catedral$","Santiago: oriente–poniente, desde la Plaza de Armas (costado norte de la Catedral) hacia los barrios Brasil y Yungay.",[-70.660,-33.438],{bt:1}],
["Av. Brasil","^Avenida Brasil$","Santiago: norte–sur, eje del Barrio Brasil, entre la Alameda y el Mapocho; pasa por la Plaza Brasil.",null,{bt:1}],
["Av. El Bosque","^Avenida El Bosque( Norte| Sur)?$","Las Condes / Providencia: norte–sur. El Bosque Norte está en el corazón de Sanhattan; hacia el sur cruza Providencia hasta Bilbao.",[-70.598,-33.418],{bt:1,gap:1.5,trMin:0.5}],
["Av. Walker Martínez","^Avenida Walker Martínez$","La Florida: oriente–poniente, desde Vicuña Mackenna hacia la precordillera.",null,{bt:1}],
["Rojas Magallanes","^Rojas Magallanes$","La Florida: oriente–poniente, al sur de Walker Martínez (estación Rojas Magallanes, L4).",null,{bt:1}],
["Av. Camilo Henríquez","^Avenida Camilo Henríquez$","Puente Alto / La Florida: norte–sur por el oriente de Puente Alto; Mall Plaza Tobalaba.",null,{bt:1}],
["Av. Gabriela","^Avenida Gabriela( Poniente| Oriente)?$","Puente Alto / La Pintana: oriente–poniente, cruza Puente Alto de lado a lado.",null,{bt:1,gap:1.5}],
["Av. Consistorial","^Avenida Consistorial$","Peñalolén: norte–sur en el sector alto, paralela a Tobalaba por el oriente.",null,{bt:1}],
["Av. Lo Ovalle","^Avenida Lo Ovalle$","Oriente–poniente en el sur: límite entre San Miguel y La Cisterna, y entre San Joaquín y La Granja (estación Lo Ovalle, L2).",null,{bt:1}],
["Av. El Parrón","^Avenida El Parrón$","La Cisterna: oriente–poniente, cruza Gran Avenida en la estación El Parrón (L2).",null,{bt:1}],
["Av. Lo Espejo","^Avenida Lo Espejo$","Lo Espejo / El Bosque / La Cisterna: oriente–poniente en el sur.",null,{bt:1}],
["Av. Eyzaguirre","^Avenida Eyzaguirre$","Puente Alto: oriente–poniente, eje principal del centro de Puente Alto.",null,{bt:1}],
["Av. Cerrillos","^Avenida Cerrillos$","Pedro Aguirre Cerda / Lo Espejo: norte–sur corta, en el límite con Cerrillos.",null,{bt:1}],
["Camino a Rinconada","^Camino a Rinconada$","Maipú: sale de la Plaza de Maipú hacia el poniente (Hospital El Carmen, Rinconada de Maipú).",null,{bt:1}],
["Av. Teniente Cruz","^Avenida Teniente Cruz$","Pudahuel / Lo Prado: norte–sur por el poniente (Persa Teniente Cruz, estación Pudahuel).",null,{bt:1}],
["Av. Lo Errázuriz","^Avenida Lo Errázuriz$","Cerrillos / Maipú / Estación Central: norte–sur por el poniente.",null,{bt:1}],
["Camino Lo Boza","^Camino Lo Boza$","Pudahuel / Renca: eje del sector industrial al nororiente del aeropuerto.",null,{bt:1}],
["Av. Gladys Marín","^Avenida Gladys Marín$","Estación Central: el tramo de la ex Pajaritos entre la Alameda (Las Rejas) y la Ruta 68.",null,{bt:1}],
["Av. Einstein","^Avenida Einstein$","Recoleta / Independencia: oriente–poniente (estación Einstein, L2).",null,{bt:1}],
["Av. Los Zapadores","^Avenida Los Zapadores$","Recoleta / Conchalí: oriente–poniente en el norte (estación Zapadores, L2).",null,{bt:1}],
["Av. Fermín Vivaceta","^Avenida Fermín Vivaceta$","Independencia / Conchalí: norte–sur, paralela a Av. Independencia por el poniente (estación Vivaceta, L3).",null,{bt:1}],
["Av. Presidente Eduardo Frei Montalva","^Avenida Presidente Eduardo Frei Montalva$","La calle lateral de la Ruta 5 Norte (Panamericana Norte): Independencia, Renca, Conchalí, Quilicura.",[-70.68,-33.42],{bt:1,gap:1.5}],
["Santos Dumont","^(Avenida )?Santos Dumont$","Recoleta / Independencia: oriente–poniente por el sector de hospitales (J.J. Aguirre, Clínica Dávila).",null,{bt:1}],
["Camino La Pirámide","^Camino La Pirámide$","Huechuraba / Vitacura: sube desde Américo Vespucio (La Pirámide) hacia Ciudad Empresarial por el cerro.",[-70.62,-33.38],{bt:1}],
["Diagonal Paraguay","^Diagonal Paraguay$","Santiago Centro: diagonal entre la Alameda (frente al cerro Santa Lucía) y Vicuña Mackenna; FEN de la U. de Chile, torres San Borja.",null,{bt:1}],
["Av. El Cerro","^Avenida El Cerro$","Providencia: cruza el Mapocho por el puente frente a Nueva Tobalaba y bordea el cerro San Cristóbal por Pedro de Valdivia Norte, hasta Los Conquistadores; estación Oasis del teleférico.",[-70.613,-33.418],{bt:1,gap:1.5}],
["Av. Francisco Bulnes Correa","^Avenida Francisco Bulnes Correa( Oriente)?$","Las Condes: norte–sur por el sector alto, desde San Damián hacia San Carlos de Apoquindo y el sur (Colegio Cordillera, U. de los Andes cerca).",null,{bt:1,gap:1.5}],
["Camino Las Flores","^Camino Las Flores$","Las Condes: oriente–poniente en el sector alto, entre Paul Harris / Estoril y San Carlos de Apoquindo (Colegio Cumbres, Rotonda Las Flores).",null,{bt:1}],
["Diagonal Las Torres","^Diagonal Las Torres$","Peñalolén: diagonal que sube hacia la precordillera; lleva a la U. Adolfo Ibáñez y al Templo Bahá'í.",[-70.525,-33.48],{bt:1,gap:1.5}],
["Av. Las Torres (poniente)","^Avenida Las Torres$","Cerro Navia / Lo Prado / Pudahuel: norte–sur por el poniente, entre Av. Neptuno y Av. Teniente Cruz, y sigue al sur hasta Maipú. Va bajo las torres de alta tensión. Ojo: hay otra Av. Las Torres en Peñalolén / Macul (la de la estación Las Torres, L4).",[-70.731,-33.44],{bt:1}],
["Av. José Miguel Infante","^(Avenida )?José Miguel Infante$","Renca: oriente–poniente, el eje principal del sector poniente de Renca, al pie del cerro. Ojo: no es José Manuel Infante (Providencia).",[-70.736,-33.407],{bt:1,gap:1.5}],
["Av. Condell (Renca)","^Avenida Condell$","Renca: norte–sur, baja desde José Miguel Infante hacia el Mapocho y Cerro Navia. Ojo: hay otra Condell en Providencia (Barrio Italia).",[-70.723,-33.411],{bt:1}],
["Av. Miraflores (Renca)","^Miraflores$","Renca: sector poniente, hacia Américo Vespucio y Pudahuel. Ojo: hay otra Miraflores en Santiago Centro.",[-70.755,-33.400],{bt:1}],
["Av. Domingo Santa María","^Avenida Domingo Santa María$","Independencia / Renca: oriente–poniente por la ribera norte del Mapocho, desde Av. Independencia hasta el centro de Renca (Plaza de Renca).",null,{bt:1,gap:1.5}],
["Av. Padre Hurtado (sur)","^(Avenida|Camino) Padre Hurtado$","El Bosque / San Bernardo: norte–sur, el antiguo camino Los Morros; baja desde La Cisterna por El Bosque y San Bernardo hacia Nos y Buin. Ojo: no es la Padre Hurtado de Las Condes.",[-70.668,-33.551],{bt:1,gap:2,trMin:1}],
["Líneas de tren (EFE)","^\\(rail\\) EFE","Vías férreas de EFE. La principal sale de Estación Central hacia el sur (Pedro Aguirre Cerda, Lo Espejo, San Bernardo, Nos, Rancagua); hay ramales al norte (Quilicura, Batuco) y al poniente (hacia Melipilla).",[-70.690,-33.50],{bt:1,kind:"tren",key:"railway"}]
];
